[package]
name = "leptos-spin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
leptos = { git = "https://github.com/leptos-rs/leptos", rev = "6014a70d0def869f12282d2df8b6c442a012964d", features = ["ssr", "spin"] }
leptos_integration_utils = { git = "https://github.com/leptos-rs/leptos", rev = "6014a70d0def869f12282d2df8b6c442a012964d" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", rev = "6014a70d0def869f12282d2df8b6c442a012964d", features = ["ssr"] }
leptos_router = { git = "https://github.com/leptos-rs/leptos", rev = "6014a70d0def869f12282d2df8b6c442a012964d", features = ["ssr"] }
routefinder = { version = "0.5.3" }
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v2.0.1" }
url = "2.4.1"

[features]
nonce = ["leptos/nonce"]
